Added missing library folder from frameworks
error: frameworks/multidex/instrumentation/Android.bp:29:1: "android-support-multidex-instrumentation" depends on undefined module "android-support-multidex"